create table global_variables
(
    id                                                  integer not null
        constraint variables_pk
            primary key,
    name                                                varchar(125),
    number_of_user_variables                            integer,
    variable_category_id                                smallint,
    default_unit_id                                     smallint,
    default_value                                       double precision,
    cause_only                                          smallint,
    client_id                                           varchar(80),
    combination_operation                               text,
    common_alias                                        varchar(125),
    created_at                                          timestamp,
    description                                         text,
    duration_of_action                                  integer,
    filling_value                                       double precision,
    image_url                                           varchar(2083),
    informational_url                                   varchar(2083),
    ion_icon                                            varchar(40),
    kurtosis                                            double precision,
    maximum_allowed_value                               double precision,
    maximum_recorded_value                              double precision,
    mean                                                double precision,
    median                                              double precision,
    minimum_allowed_value                               double precision,
    minimum_recorded_value                              double precision,
    number_of_aggregate_correlations_as_cause           integer,
    most_common_original_unit_id                        integer,
    most_common_value                                   double precision,
    number_of_aggregate_correlations_as_effect          integer,
    number_of_unique_values                             integer,
    onset_delay                                         integer,
    outcome                                             smallint,
    parent_id                                           integer,
    price                                               double precision,
    product_url                                         varchar(2083),
    second_most_common_value                            double precision,
    skewness                                            double precision,
    standard_deviation                                  double precision,
    status                                              varchar(25),
    third_most_common_value                             double precision,
    updated_at                                          timestamp,
    variance                                            double precision,
    most_common_connector_id                            integer,
    synonyms                                            varchar(600),
    wikipedia_url                                       varchar(2083),
    brand_name                                          varchar(125),
    valence                                             text,
    wikipedia_title                                     varchar(100),
    number_of_tracking_reminders                        integer,
    upc_12                                              varchar(255),
    upc_14                                              varchar(255),
    number_common_tagged_by                             integer,
    number_of_common_tags                               integer,
    deleted_at                                          timestamp,
    most_common_source_name                             varchar(255),
    data_sources_count                                  text,
    optimal_value_message                               varchar(500),
    best_cause_variable_id                              integer,
    best_effect_variable_id                             integer,
    common_maximum_allowed_daily_value                  double precision,
    common_minimum_allowed_daily_value                  double precision,
    common_minimum_allowed_non_zero_value               double precision,
    minimum_allowed_seconds_between_measurements        integer,
    average_seconds_between_measurements                integer,
    median_seconds_between_measurements                 integer,
    number_of_raw_measurements_with_tags_joins_children integer,
    additional_meta_data                                text,
    manual_tracking                                     smallint,
    analysis_settings_modified_at                       timestamp,
    newest_data_at                                      timestamp,
    analysis_requested_at                               timestamp,
    reason_for_analysis                                 varchar(255),
    analysis_started_at                                 timestamp,
    analysis_ended_at                                   timestamp,
    user_error_message                                  text,
    internal_error_message                              text,
    latest_tagged_measurement_start_at                  timestamp,
    earliest_tagged_measurement_start_at                timestamp,
    latest_non_tagged_measurement_start_at              timestamp,
    earliest_non_tagged_measurement_start_at            timestamp,
    wp_post_id                                          bigint,
    number_of_soft_deleted_measurements                 integer,
    charts                                              json,
    creator_user_id                                     bigint,
    best_aggregate_correlation_id                       integer,
    filling_type                                        text,
    number_of_outcome_population_studies                integer,
    number_of_predictor_population_studies              integer,
    number_of_applications_where_outcome_variable       integer,
    number_of_applications_where_predictor_variable     integer,
    number_of_common_tags_where_tag_variable            integer,
    number_of_common_tags_where_tagged_variable         integer,
    number_of_outcome_case_studies                      integer,
    number_of_predictor_case_studies                    integer,
    number_of_measurements                              integer,
    number_of_studies_where_cause_variable              integer,
    number_of_studies_where_effect_variable             integer,
    number_of_tracking_reminder_notifications           integer,
    number_of_user_tags_where_tag_variable              integer,
    number_of_user_tags_where_tagged_variable           integer,
    number_of_variables_where_best_cause_variable       integer,
    number_of_variables_where_best_effect_variable      integer,
    number_of_votes_where_cause_variable                integer,
    number_of_votes_where_effect_variable               integer,
    number_of_users_where_primary_outcome_variable      integer,
    deletion_reason                                     varchar(280),
    maximum_allowed_daily_value                         double precision,
    record_size_in_kb                                   integer,
    number_of_common_joined_variables                   integer,
    number_of_common_ingredients                        integer,
    number_of_common_foods                              integer,
    number_of_common_children                           integer,
    number_of_common_parents                            integer,
    number_of_user_joined_variables                     integer,
    number_of_user_ingredients                          integer,
    number_of_user_foods                                integer,
    number_of_user_children                             integer,
    number_of_user_parents                              integer,
    is_public                                           smallint,
    sort_order                                          integer,
    is_goal                                             smallint,
    controllable                                        smallint,
    boring                                              smallint,
    slug                                                varchar(200),
    canonical_variable_id                               integer,
    predictor                                           smallint,
    source_url                                          varchar(2083)
);


